apiVersion: v1
kind: Pod
metadata:
  name: prod-pod
spec:
  restartPolicy: Always
  volumes:
  - name: web-root
    emptyDir: {}
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: web-root
      mountPath: /usr/share/nginx/html
  - name: scraper
    image: alpine:latest
    command: ["/bin/sh", "-c"]
    args:
      - |
        apk add --no-cache curl;
        while true; do
          curl -s https://raw.githubusercontent.com/kubernetes/kubernetes/master/README.md > /usr/share/nginx/html/index.html;
          sleep 10;
        done
    volumeMounts:
    - name: web-root
      mountPath: /usr/share/nginx/html
