apiVersion: v1
kind: Pod
metadata:
  name: lab3-static-pod
  namespace: default
  labels:
    role: my-app
spec:
  restartPolicy: Always
  containers:
    - name: my-nginx
      image: nginx:latest
      ports:
        - name: web
          containerPort: 80
          hostPort: 80

    - name: my-postgres
      image: postgres:13
      ports:
        - name: db
          containerPort: 5432
      env:
        - name: POSTGRES_PASSWORD
          value: "admin"
