apiVersion: v1
kind: Pod
metadata:
  name: lab3-static-pod
spec:
  hostNetwork: true
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: my-nginx
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  - name: my-scraper
    image: alpine:latest
    command: ["/bin/sh", "-c"]
    args:
      - |
        apk add --no-cache curl;
        while true; do
          curl -s https://raw.githubusercontent.com/kubernetes/kubernetes/master/README.md > /usr/share/nginx/html/index.html;
          sleep 10;
        done
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "64Mi"
        cpu: "100m"
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
